### ISSUE TITLE
Update PyPI Integration

### ISSUE THREAD

**Issue by rajadain** [azavea/python-omgeo#71]
With recent changes to PyPI trusted publishers, we need to update the CI to use that instead of the old non-functional username / password setup.

Update the integration so that releases may publish to PyPI again.

**Comment by JN-Hernandez** [comment]
# WorkPlan

## Summary

The `python-omgeo` Python packages is published via the Azavea PyPI account, however recent builds of these projects are failing because PyPI has changed from username/password authentication to token based and trusted-publisher based authentication.  This workplan is to document updating this integration.

## Steps

- [x] 1. Log in to TestPyPi using the `TestPyPi Python Package Index` credentials within **1Password**
- [x] 2. Click the `azavea` user in the top-right hand corner, then select `Your Projects` from the dropdown menu
- [x] 3. Traverse to `Publishing`, then scroll down to **Add a new publisher**
- [x] 4. Fill in the **Owner**, **Repository name**, and **Workflow name**, then click `Next`
> [!Note]
> Only use the actual repository name, not full GitHub URL nor the `azavea/` prefix.
- [x] 5. Log in to PyPI using the `Python Package Index (PyPi)` credentials within **1Password**
- [x] 6. Repeat steps 2-4 of this workplan to add a new publisher
- [x] 7. Update the `release.yml` GitHub Workflow to upload the release to TestPyPI
> [!Tip]
> Review PR #72 to see what changes in the file were made/needed.
- [x] 8. Update the `CHANGES.txt` file to document the update
- [ ] 9. Move through the [PR process](https://github.com/azavea/python-omgeo/pull/72) and confirm upload works for TestPyPI
- [ ] 8. Once approved, update the `release.yml` file to instead upload the release to PyPI
- [ ] 9. Move through the Git Flow process to update the release

## Criteria for Success

- [ ] 1. Upload of the release to TestPyPI works as expected
- [ ] 2. Upload of the release to PyPI works as expected

## Risk

Low Risk
1. Failure to implement this change will result in the release upload to PyPI not working

## Rollback

1. n/a - failure to implement this change will result in the release upload to PyPI not working

## Additional Details

- PyPI Integration Documentation: [Publishing to PyPI with a Trusted Publisher](https://docs.pypi.org/trusted-publishers/)
- GitHub Actions Documentation: [Triggering a workflow](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow)
